export DEVDIR=$HOME/Development
export ITERM_INT=false
export GPG_TTY=$(tty)
export GPG_KEY=9073DEB608346BA4
export GNUPGHOME=${HOME}/.gnupg
export PATH=$HOME/.local/bin:$PATH
export XDG_CONFIG_HOME=$HOME/.config
if [[ -v WSLENV ]]; then
    if [[ "$TERM_PROG" == "winterm" ]]; then
        export NF_SAFE=true
    elif [[ $WSLENV == "WT_SESSION::WT_PROFILE_ID" ]]; then
        export NF_SAFE=true
    else
        export NF_SAFE=false
    fi
else
    if [[ "$TERM" == "linux" && -z $DISPLAY ]]; then
        export TERM_PROG='linux_console'
        export NF_SAFE=false
    elif [[ $TERM_PROG == 'linux_console' ]]; then
        export NF_SAFE=false
    else
        export NF_SAFE=true
    fi
fi

export MANUFACTURER=UNKNOWN
if [[ -v WSLENV ]]; then
      export MANUFACTURER=$(powershell.exe -command "(Get-WmiObject -Class:Win32_ComputerSystem).Manufacturer")
elif [ -f /sys/devices/virtual/dmi/id/sys_vendor ]; then
      export MANUFACTURER=$(cat /sys/devices/virtual/dmi/id/sys_vendor)
fi

# Setup homebrew on the mac
if [[ $(uname) == "Darwin" ]]; then
    eval $(/opt/homebrew/bin/brew shellenv)
    # Build MacOS Path
    export PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
fi

# Setup Cargo and Rust
source ~/.cargo/env

# Bug in pip3 means it looks for a keyring
# if it queries kwallet and no keyring exists
# it prompts kwallet to create one.  This envvar
# stops that from happening.
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

export PAGER=bat
export EDITOR=nvim

# Source local environment variables to override
# any of the envars defined here.
source ~/.config/dot-files/zsh/zshenv.local
. "$HOME/.cargo/env"
