#
# Source files
#

if [ -f "${HOME}/.config/dotfiles/.optional" ]; then
    OPTIONAL=$(cat .optional.txt)
fi

for f in "${HOME}"/.config/dotfiles/zsh.d/*.zsh; do
	if [[ " ${OPTIONAL[@]} " =~ " ${f} " ]]; then
		continue
	fi
	source "${f}"
done
