#
# Source files
#

if [ -f "${HOME}/.config/dot-files/zsh/.optional" ]; then
    OPTIONAL=$(cat .optional.txt)
fi

for f in "${HOME}"/.config/dot-files/zsh/zsh.d/*.zsh; do
	if [[ " ${OPTIONAL[@]} " =~ " ${f} " ]]; then
		continue
	fi
	source "${f}"
done

if [ -f "${HOME}/.iterm2_shell_integration.zsh" ]; then
	test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi
